import { Item } from "./app/shared/models/Item";

export const sampleItem: Item[] = [
  {
    id:'1',
    name: 'Monstera Monkey Mask',
    price: 55,
    description: 'Nazwę zawdzięcza liściom przypominającym małpi pyszczek. Dorasta maksymalnie do około metra. Można ją prowadzić na paliku, ale będzie też czarująco wyglądać zwisając w makramie.',
    favorite: false,
    stars: 4.5,
    imageUrl: 'assets/plant-1.jpg',
    tags: ['Monstera', 'Vines', 'SimpleCare', 'DiffusedLight', 'MonkeyMask'],
  },
  {
    id:'2',
    name: 'Philodendrons',
    price: 55,
    description: 'Przykuwająca wzrok odmiana filodendrona o zwartym pokroju i przepięknie wybarwionych liściach. Dolne liście maja głęboki ciemnozielony kolor, a górne biało-zielony z wyraźnie zarysowanym paskowaniem',
    favorite: true,
    stars: 4.7,
    imageUrl: 'assets/plant-2.jpg',
    tags: ['Philodendrons', 'Vines', 'SimpleCare', 'DiffusedLight', 'Birkin'],
  },
  {
    id:'3',
    name: 'Alocasia baginda Pink Dragon',
    price: 99,
    description: 'Różowa smoczyca czyli Alocasia Pink Dragon to niezwykle piękna roślina. Cechą charakterystyczną są różowe łodygi, z których wyrastają liście o kształcie i ornamentyce rozpoznawalnej dla alokazji.',
    favorite: false,
    stars: 4.6,
    imageUrl: 'assets/plant-3.jpg',
    tags: ['Alocasia', 'DiffusedLight'],
  },
  {
    id:'4',
    name: 'Syngonium Arrow',
    price: 35,
    description: 'Syngonium alias Zroślicha to piękna roślina doniczkowa o strzałkowatych liściach, na których w odmianie Arrow łączy się zieleń z bielą. Jest łatwe w pielęgnacji i dość odporne, należy jednak pamiętać że lubi zraszanie i wysoką wilgotność powietrza. Za odtworzenie dżunglowych warunków naturalnych odwdzięczy się bujnym wzrostem',
    favorite: true,
    stars: 4.3,
    imageUrl: 'assets/plant-4.jpg',
    tags: ['Syngonium', 'Vines', 'SimpleCare', 'DiffusedLight'],
  },
  {
    id:'5',
    name: 'Asplenium Parvati',
    price: 39,
    description: 'Asplenium albo Zanokcica to piękna i bezpieczna dla naszych pupili roślina. W dodatku ma dobroczynny wpływ na jakość powietrza; łagodzi promieniowanie emitowane przez komputery i inne sprzęty elektryczne. Przydomek Parvati pochodzi od hinduskiej bogini miłości, gdyż na Półwyspie Indyjskim skąd pochodzi jest częstym elementem wiązanek ślubnych.',
    favorite: false,
    stars: 3.0,
    imageUrl: 'assets/plant-5.jpg',
    tags: ['PurifyingTheAir', 'Ferns',  'SimpleCare', 'DiffusedLight', 'AnimalsSave'],
  },
  {
    id:'6',
    name: 'Gasteraloe Aveo',
    price: 24,
    description: 'Gasteraloe Aveo to bardzo ciekawy i rzadko dostępny w sprzedaży sukulent! Pochodzi od dwóch roślin – gasterii i aloesu. Z tego połączenia powstały mięsiste, nakrapiane liście tego sukulenta, a do tego jest to hybryda bardzo łatwa w uprawie. Pamiętajmy jednak, aby zapewnić tej roślinie doniczkowej jasne stanowisko i mocno przepuszczalne podłoże.',
    favorite: false,
    stars: 4.0,
    imageUrl: 'assets/plant-6.jpg',
    tags: ['Gasteraloe', 'PottedWithSunnyLocation', 'Succulents', 'SimpleCare', 'DiffusedLight', 'AnimalsSave'],
  },
]
