import { Item } from "./app/shared/models/Item";

export const sampleItem: Item[] = [
  {
    id:'1',
    name: 'Pizza Pepperoni',
    price: 10,
    description: '10-20',
    favorite: false,
    stars: 4.5,
    imageUrl: 'assets/plant-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'2',
    name: 'Meatball',
    price: 20,
    description: '20-30',
    favorite: true,
    stars: 4.7,
    imageUrl: 'assets/plant-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'3',
    name: 'Hamburger',
    price: 5,
    description: '10-15',
    favorite: false,
    stars: 3.5,
    imageUrl: 'assets/plant-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 2,
    description: '15-20',
    favorite: true,
    stars: 3.3,
    imageUrl: 'assets/plant-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 11,
    description: '40-50',
    favorite: false,
    stars: 3.0,
    imageUrl: 'assets/plant-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 9,
    description: '40-50',
    favorite: false,
    stars: 4.0,
    imageUrl: 'assets/plant-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
]
